[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  # Corrected parameter (lowercase 'u' in 'baseUrl')
  baseUrl = "https://nabasa-amos.netlify.app/"

  # Optional settings (uncomment if needed)
  # trailingSlash = true
  # prettyURLs = true
  # exclude = ["/admin/*", "/private/*"]